SMS_EXECUTIVE started SMS_CLOUDCONNECTION as thread ID 8836 (0x2284).  $$<SMS_CLOUDCONNECTION><02-26-2023 19:53:32.215+480><thread=3604 (0xE14)>
Initializing Task Execution Manager instance as SMS_CLOUDCONNECTION.  $$<SMS_CLOUDCONNECTION><02-26-2023 19:53:32.215+480><thread=4212 (0x1074)>
Starting component SMS_CLOUDCONNECTION~~  $$<SMS_CLOUDCONNECTION><02-26-2023 19:53:32.215+480><thread=4212 (0x1074)>
Component SMS_CLOUDCONNECTION started successfully.~~  $$<SMS_CLOUDCONNECTION><02-26-2023 19:53:32.215+480><thread=4212 (0x1074)>
ERROR: Found exception System.AggregateException: One or more errors occurred. ---> System.ArgumentNullException: Value cannot be null.~~Parameter name: path2~~~~Server stack trace: ~~   at System.IO.Path.Combine(String path1, String path2)~~   at Microsoft.ConfigurationManagement.ApplicationManagement.Wsfb.Sync.SyncConfig.get_OutboxDirectory()~~   at Microsoft.ConfigurationManagement.ApplicationManagement.Wsfb.Sync.SyncWorker.SetupOutbox()~~   at Microsoft.ConfigurationManagement.ApplicationManagement.Wsfb.Sync.SyncWorker.Start(String componentName)~~   at Microsoft.ConfigurationManager.TaskExecutionManager.TaskExecution.InvokeWorker(String assemblyToLoad, String typeToLoad, String componentName)~~   at System.Runtime.Remoting.Messaging.Message.Dispatch(Object target)~~   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)~~~~Exception rethrown at [0]: ~~   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)~~   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)~~   at Microsoft.ConfigurationManager.TaskExecutionManager.TaskExecution.InvokeWorker(String assemblyToLoad, String typeToLoad, String componentName)~~   at System.Threading.Tasks.Task.Execute()~~   --- End of inner exception stack trace ---~~   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)~~   at Microsoft.ConfigurationManager.TaskExecutionManager.TaskExecution.Initialize(String componentName)~~---> (Inner Exception #0) System.ArgumentNullException: Value cannot be null.~~Parameter name: path2~~~~Server stack trace: ~~   at System.IO.Path.Combine(String path1, String path2)~~   at Microsoft.ConfigurationManagement.ApplicationManagement.Wsfb.Sync.SyncConfig.get_OutboxDirectory()~~   at Microsoft.ConfigurationManagement.ApplicationManagement.Wsfb.Sync.SyncWorker.SetupOutbox()~~   at Microsoft.ConfigurationManagement.ApplicationManagement.Wsfb.Sync.SyncWorker.Start(String componentName)~~   at Microsoft.ConfigurationManager.TaskExecutionManager.TaskExecution.InvokeWorker(String assemblyToLoad, String typeToLoad, String componentName)~~   at System.Runtime.Remoting.Messaging.Message.Dispatch(Object target)~~   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)~~~~Exception rethrown at [0]: ~~   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)~~   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)~~   at Microsoft.ConfigurationManager.TaskExecutionManager.TaskExecution.InvokeWorker(String assemblyToLoad, String typeToLoad, String componentName)~~   at System.Threading.Tasks.Task.Execute()<---~~~~  $$<SMS_CLOUDCONNECTION><02-26-2023 19:53:32.309+480><thread=4212 (0x1074)>
ERROR: Found inner exception System.ArgumentNullException: Value cannot be null.~~Parameter name: path2~~~~Server stack trace: ~~   at System.IO.Path.Combine(String path1, String path2)~~   at Microsoft.ConfigurationManagement.ApplicationManagement.Wsfb.Sync.SyncConfig.get_OutboxDirectory()~~   at Microsoft.ConfigurationManagement.ApplicationManagement.Wsfb.Sync.SyncWorker.SetupOutbox()~~   at Microsoft.ConfigurationManagement.ApplicationManagement.Wsfb.Sync.SyncWorker.Start(String componentName)~~   at Microsoft.ConfigurationManager.TaskExecutionManager.TaskExecution.InvokeWorker(String assemblyToLoad, String typeToLoad, String componentName)~~   at System.Runtime.Remoting.Messaging.Message.Dispatch(Object target)~~   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)~~~~Exception rethrown at [0]: ~~   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)~~   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)~~   at Microsoft.ConfigurationManager.TaskExecutionManager.TaskExecution.InvokeWorker(String assemblyToLoad, String typeToLoad, String componentName)~~   at System.Threading.Tasks.Task.Execute()~~  $$<SMS_CLOUDCONNECTION><02-26-2023 19:53:32.309+480><thread=4212 (0x1074)>
The host's stop has been called, shutting down 2 workers.~~  $$<SMS_CLOUDCONNECTION><02-26-2023 19:53:32.309+480><thread=4212 (0x1074)>
Successfully shut down the workers.~~  $$<SMS_CLOUDCONNECTION><02-26-2023 19:53:32.309+480><thread=4212 (0x1074)>
Failed to initialize worker with error =  Unknown error 0x80131500  $$<SMS_CLOUDCONNECTION><02-26-2023 19:53:32.324+480><thread=4212 (0x1074)>
Thread for Task Execution Manager has stopped.  $$<SMS_CLOUDCONNECTION><02-26-2023 19:53:32.324+480><thread=4212 (0x1074)>
Stop for thread SMS_CLOUDCONNECTION has been called or Task Execution Manager thread has shutdown.  $$<SMS_CLOUDCONNECTION><02-26-2023 19:53:32.324+480><thread=8836 (0x2284)>
The host's stop has been called, shutting down 0 workers.~~  $$<SMS_CLOUDCONNECTION><02-26-2023 19:53:32.324+480><thread=8836 (0x2284)>
Successfully shut down the workers.~~  $$<SMS_CLOUDCONNECTION><02-26-2023 19:53:32.324+480><thread=8836 (0x2284)>
End main SMS_CLOUDCONNECTION thread  $$<SMS_CLOUDCONNECTION><02-26-2023 19:53:32.324+480><thread=8836 (0x2284)>
SMS_EXECUTIVE started SMS_CLOUDCONNECTION as thread ID 5680 (0x1630).  $$<SMS_CLOUDCONNECTION><02-26-2023 19:55:26.142+480><thread=3768 (0xEB8)>
Initializing Task Execution Manager instance as SMS_CLOUDCONNECTION.  $$<SMS_CLOUDCONNECTION><02-26-2023 19:55:26.298+480><thread=5564 (0x15BC)>
Starting component SMS_CLOUDCONNECTION~~  $$<SMS_CLOUDCONNECTION><02-26-2023 19:55:26.361+480><thread=5564 (0x15BC)>
Component SMS_CLOUDCONNECTION started successfully.~~  $$<SMS_CLOUDCONNECTION><02-26-2023 19:55:26.517+480><thread=5564 (0x15BC)>
ERROR: Found exception System.AggregateException: One or more errors occurred. ---> System.ArgumentNullException: Value cannot be null.~~Parameter name: path2~~~~Server stack trace: ~~   at System.IO.Path.Combine(String path1, String path2)~~   at Microsoft.ConfigurationManagement.ApplicationManagement.Wsfb.Sync.SyncConfig.get_OutboxDirectory()~~   at Microsoft.ConfigurationManagement.ApplicationManagement.Wsfb.Sync.SyncWorker.SetupOutbox()~~   at Microsoft.ConfigurationManagement.ApplicationManagement.Wsfb.Sync.SyncWorker.Start(String componentName)~~   at Microsoft.ConfigurationManager.TaskExecutionManager.TaskExecution.InvokeWorker(String assemblyToLoad, String typeToLoad, String componentName)~~   at System.Runtime.Remoting.Messaging.Message.Dispatch(Object target)~~   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)~~~~Exception rethrown at [0]: ~~   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)~~   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)~~   at Microsoft.ConfigurationManager.TaskExecutionManager.TaskExecution.InvokeWorker(String assemblyToLoad, String typeToLoad, String componentName)~~   at System.Threading.Tasks.Task.Execute()~~   --- End of inner exception stack trace ---~~   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)~~   at Microsoft.ConfigurationManager.TaskExecutionManager.TaskExecution.Initialize(String componentName)~~---> (Inner Exception #0) System.ArgumentNullException: Value cannot be null.~~Parameter name: path2~~~~Server stack trace: ~~   at System.IO.Path.Combine(String path1, String path2)~~   at Microsoft.ConfigurationManagement.ApplicationManagement.Wsfb.Sync.SyncConfig.get_OutboxDirectory()~~   at Microsoft.ConfigurationManagement.ApplicationManagement.Wsfb.Sync.SyncWorker.SetupOutbox()~~   at Microsoft.ConfigurationManagement.ApplicationManagement.Wsfb.Sync.SyncWorker.Start(String componentName)~~   at Microsoft.ConfigurationManager.TaskExecutionManager.TaskExecution.InvokeWorker(String assemblyToLoad, String typeToLoad, String componentName)~~   at System.Runtime.Remoting.Messaging.Message.Dispatch(Object target)~~   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)~~~~Exception rethrown at [0]: ~~   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)~~   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)~~   at Microsoft.ConfigurationManager.TaskExecutionManager.TaskExecution.InvokeWorker(String assemblyToLoad, String typeToLoad, String componentName)~~   at System.Threading.Tasks.Task.Execute()<---~~~~  $$<SMS_CLOUDCONNECTION><02-26-2023 19:55:26.798+480><thread=5564 (0x15BC)>
ERROR: Found inner exception System.ArgumentNullException: Value cannot be null.~~Parameter name: path2~~~~Server stack trace: ~~   at System.IO.Path.Combine(String path1, String path2)~~   at Microsoft.ConfigurationManagement.ApplicationManagement.Wsfb.Sync.SyncConfig.get_OutboxDirectory()~~   at Microsoft.ConfigurationManagement.ApplicationManagement.Wsfb.Sync.SyncWorker.SetupOutbox()~~   at Microsoft.ConfigurationManagement.ApplicationManagement.Wsfb.Sync.SyncWorker.Start(String componentName)~~   at Microsoft.ConfigurationManager.TaskExecutionManager.TaskExecution.InvokeWorker(String assemblyToLoad, String typeToLoad, String componentName)~~   at System.Runtime.Remoting.Messaging.Message.Dispatch(Object target)~~   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)~~~~Exception rethrown at [0]: ~~   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)~~   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)~~   at Microsoft.ConfigurationManager.TaskExecutionManager.TaskExecution.InvokeWorker(String assemblyToLoad, String typeToLoad, String componentName)~~   at System.Threading.Tasks.Task.Execute()~~  $$<SMS_CLOUDCONNECTION><02-26-2023 19:55:26.814+480><thread=5564 (0x15BC)>
The host's stop has been called, shutting down 2 workers.~~  $$<SMS_CLOUDCONNECTION><02-26-2023 19:55:26.814+480><thread=5564 (0x15BC)>
Successfully shut down the workers.~~  $$<SMS_CLOUDCONNECTION><02-26-2023 19:55:26.845+480><thread=5564 (0x15BC)>
Failed to initialize worker with error =  Unknown error 0x80131500  $$<SMS_CLOUDCONNECTION><02-26-2023 19:55:26.845+480><thread=5564 (0x15BC)>
Thread for Task Execution Manager has stopped.  $$<SMS_CLOUDCONNECTION><02-26-2023 19:55:26.845+480><thread=5564 (0x15BC)>
Stop for thread SMS_CLOUDCONNECTION has been called or Task Execution Manager thread has shutdown.  $$<SMS_CLOUDCONNECTION><02-26-2023 19:55:26.861+480><thread=5680 (0x1630)>
The host's stop has been called, shutting down 0 workers.~~  $$<SMS_CLOUDCONNECTION><02-26-2023 19:55:26.861+480><thread=5680 (0x1630)>
Successfully shut down the workers.~~  $$<SMS_CLOUDCONNECTION><02-26-2023 19:55:26.861+480><thread=5680 (0x1630)>
End main SMS_CLOUDCONNECTION thread  $$<SMS_CLOUDCONNECTION><02-26-2023 19:55:26.861+480><thread=5680 (0x1630)>
SMS_EXECUTIVE started SMS_CLOUDCONNECTION as thread ID 8120 (0x1FB8).  $$<SMS_CLOUDCONNECTION><02-26-2023 19:55:31.845+480><thread=3768 (0xEB8)>
Initializing Task Execution Manager instance as SMS_CLOUDCONNECTION.  $$<SMS_CLOUDCONNECTION><02-26-2023 19:55:31.845+480><thread=8116 (0x1FB4)>
Starting component SMS_CLOUDCONNECTION~~  $$<SMS_CLOUDCONNECTION><02-26-2023 19:55:31.845+480><thread=8116 (0x1FB4)>
Component SMS_CLOUDCONNECTION started successfully.~~  $$<SMS_CLOUDCONNECTION><02-26-2023 19:55:31.845+480><thread=8116 (0x1FB4)>
ERROR: Found exception System.AggregateException: One or more errors occurred. ---> System.ArgumentNullException: Value cannot be null.~~Parameter name: path2~~~~Server stack trace: ~~   at System.IO.Path.Combine(String path1, String path2)~~   at Microsoft.ConfigurationManagement.ApplicationManagement.Wsfb.Sync.SyncConfig.get_OutboxDirectory()~~   at Microsoft.ConfigurationManagement.ApplicationManagement.Wsfb.Sync.SyncWorker.SetupOutbox()~~   at Microsoft.ConfigurationManagement.ApplicationManagement.Wsfb.Sync.SyncWorker.Start(String componentName)~~   at Microsoft.ConfigurationManager.TaskExecutionManager.TaskExecution.InvokeWorker(String assemblyToLoad, String typeToLoad, String componentName)~~   at System.Runtime.Remoting.Messaging.Message.Dispatch(Object target)~~   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)~~~~Exception rethrown at [0]: ~~   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)~~   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)~~   at Microsoft.ConfigurationManager.TaskExecutionManager.TaskExecution.InvokeWorker(String assemblyToLoad, String typeToLoad, String componentName)~~   at System.Threading.Tasks.Task.Execute()~~   --- End of inner exception stack trace ---~~   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)~~   at Microsoft.ConfigurationManager.TaskExecutionManager.TaskExecution.Initialize(String componentName)~~---> (Inner Exception #0) System.ArgumentNullException: Value cannot be null.~~Parameter name: path2~~~~Server stack trace: ~~   at System.IO.Path.Combine(String path1, String path2)~~   at Microsoft.ConfigurationManagement.ApplicationManagement.Wsfb.Sync.SyncConfig.get_OutboxDirectory()~~   at Microsoft.ConfigurationManagement.ApplicationManagement.Wsfb.Sync.SyncWorker.SetupOutbox()~~   at Microsoft.ConfigurationManagement.ApplicationManagement.Wsfb.Sync.SyncWorker.Start(String componentName)~~   at Microsoft.ConfigurationManager.TaskExecutionManager.TaskExecution.InvokeWorker(String assemblyToLoad, String typeToLoad, String componentName)~~   at System.Runtime.Remoting.Messaging.Message.Dispatch(Object target)~~   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)~~~~Exception rethrown at [0]: ~~   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)~~   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)~~   at Microsoft.ConfigurationManager.TaskExecutionManager.TaskExecution.InvokeWorker(String assemblyToLoad, String typeToLoad, String componentName)~~   at System.Threading.Tasks.Task.Execute()<---~~~~  $$<SMS_CLOUDCONNECTION><02-26-2023 19:55:44.048+480><thread=8116 (0x1FB4)>
ERROR: Found inner exception System.ArgumentNullException: Value cannot be null.~~Parameter name: path2~~~~Server stack trace: ~~   at System.IO.Path.Combine(String path1, String path2)~~   at Microsoft.ConfigurationManagement.ApplicationManagement.Wsfb.Sync.SyncConfig.get_OutboxDirectory()~~   at Microsoft.ConfigurationManagement.ApplicationManagement.Wsfb.Sync.SyncWorker.SetupOutbox()~~   at Microsoft.ConfigurationManagement.ApplicationManagement.Wsfb.Sync.SyncWorker.Start(String componentName)~~   at Microsoft.ConfigurationManager.TaskExecutionManager.TaskExecution.InvokeWorker(String assemblyToLoad, String typeToLoad, String componentName)~~   at System.Runtime.Remoting.Messaging.Message.Dispatch(Object target)~~   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)~~~~Exception rethrown at [0]: ~~   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)~~   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)~~   at Microsoft.ConfigurationManager.TaskExecutionManager.TaskExecution.InvokeWorker(String assemblyToLoad, String typeToLoad, String componentName)~~   at System.Threading.Tasks.Task.Execute()~~  $$<SMS_CLOUDCONNECTION><02-26-2023 19:55:44.048+480><thread=8116 (0x1FB4)>
The host's stop has been called, shutting down 2 workers.~~  $$<SMS_CLOUDCONNECTION><02-26-2023 19:55:44.048+480><thread=8116 (0x1FB4)>
WARNING: Successfully stopped worker Microsoft.ConfigurationManager.CloudConnection.STSSync.STSSyncWorker~~  $$<SMS_CLOUDCONNECTION><02-26-2023 19:55:44.048+480><thread=8116 (0x1FB4)>
UnSubscribed from Registry Hive: LocalMachine, KeyPath: SOFTWARE\Microsoft\SMS\Components\SMS_CLOUDCONNECTION, FilterType: NameChange, ValueChange, WatchSubTree: True~~  $$<SMS_CLOUDCONNECTION><02-26-2023 19:55:44.064+480><thread=8116 (0x1FB4)>
WARNING: Successfully stopped worker Microsoft.ConfigurationManager.CoMgmtGraphConnector.CoMgmtGraphConnectorWorker~~  $$<SMS_CLOUDCONNECTION><02-26-2023 19:55:44.064+480><thread=8116 (0x1FB4)>
Successfully shut down the workers.~~  $$<SMS_CLOUDCONNECTION><02-26-2023 19:55:44.064+480><thread=8116 (0x1FB4)>
Failed to initialize worker with error =  Unknown error 0x80131500  $$<SMS_CLOUDCONNECTION><02-26-2023 19:55:44.064+480><thread=8116 (0x1FB4)>
Thread for Task Execution Manager has stopped.  $$<SMS_CLOUDCONNECTION><02-26-2023 19:55:44.064+480><thread=8116 (0x1FB4)>
Stop for thread SMS_CLOUDCONNECTION has been called or Task Execution Manager thread has shutdown.  $$<SMS_CLOUDCONNECTION><02-26-2023 19:55:44.064+480><thread=8120 (0x1FB8)>
The host's stop has been called, shutting down 0 workers.~~  $$<SMS_CLOUDCONNECTION><02-26-2023 19:55:44.064+480><thread=8120 (0x1FB8)>
Successfully shut down the workers.~~  $$<SMS_CLOUDCONNECTION><02-26-2023 19:55:44.064+480><thread=8120 (0x1FB8)>
End main SMS_CLOUDCONNECTION thread  $$<SMS_CLOUDCONNECTION><02-26-2023 19:55:44.064+480><thread=8120 (0x1FB8)>
SMS_EXECUTIVE started SMS_CLOUDCONNECTION as thread ID 6364 (0x18DC).  $$<SMS_CLOUDCONNECTION><02-26-2023 19:56:03.674+480><thread=3488 (0xDA0)>
Initializing Task Execution Manager instance as SMS_CLOUDCONNECTION.  $$<SMS_CLOUDCONNECTION><02-26-2023 19:56:03.784+480><thread=5988 (0x1764)>
Starting component SMS_CLOUDCONNECTION~~  $$<SMS_CLOUDCONNECTION><02-26-2023 19:56:03.830+480><thread=5988 (0x1764)>
Component SMS_CLOUDCONNECTION started successfully.~~  $$<SMS_CLOUDCONNECTION><02-26-2023 19:56:03.940+480><thread=5988 (0x1764)>
ERROR: Found exception System.AggregateException: One or more errors occurred. ---> System.ArgumentNullException: Value cannot be null.~~Parameter name: path2~~~~Server stack trace: ~~   at System.IO.Path.Combine(String path1, String path2)~~   at Microsoft.ConfigurationManagement.ApplicationManagement.Wsfb.Sync.SyncConfig.get_OutboxDirectory()~~   at Microsoft.ConfigurationManagement.ApplicationManagement.Wsfb.Sync.SyncWorker.SetupOutbox()~~   at Microsoft.ConfigurationManagement.ApplicationManagement.Wsfb.Sync.SyncWorker.Start(String componentName)~~   at Microsoft.ConfigurationManager.TaskExecutionManager.TaskExecution.InvokeWorker(String assemblyToLoad, String typeToLoad, String componentName)~~   at System.Runtime.Remoting.Messaging.Message.Dispatch(Object target)~~   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)~~~~Exception rethrown at [0]: ~~   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)~~   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)~~   at Microsoft.ConfigurationManager.TaskExecutionManager.TaskExecution.InvokeWorker(String assemblyToLoad, String typeToLoad, String componentName)~~   at System.Threading.Tasks.Task.Execute()~~   --- End of inner exception stack trace ---~~   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)~~   at Microsoft.ConfigurationManager.TaskExecutionManager.TaskExecution.Initialize(String componentName)~~---> (Inner Exception #0) System.ArgumentNullException: Value cannot be null.~~Parameter name: path2~~~~Server stack trace: ~~   at System.IO.Path.Combine(String path1, String path2)~~   at Microsoft.ConfigurationManagement.ApplicationManagement.Wsfb.Sync.SyncConfig.get_OutboxDirectory()~~   at Microsoft.ConfigurationManagement.ApplicationManagement.Wsfb.Sync.SyncWorker.SetupOutbox()~~   at Microsoft.ConfigurationManagement.ApplicationManagement.Wsfb.Sync.SyncWorker.Start(String componentName)~~   at Microsoft.ConfigurationManager.TaskExecutionManager.TaskExecution.InvokeWorker(String assemblyToLoad, String typeToLoad, String componentName)~~   at System.Runtime.Remoting.Messaging.Message.Dispatch(Object target)~~   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)~~~~Exception rethrown at [0]: ~~   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)~~   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)~~   at Microsoft.ConfigurationManager.TaskExecutionManager.TaskExecution.InvokeWorker(String assemblyToLoad, String typeToLoad, String componentName)~~   at System.Threading.Tasks.Task.Execute()<---~~~~  $$<SMS_CLOUDCONNECTION><02-26-2023 19:56:04.252+480><thread=5988 (0x1764)>
ERROR: Found inner exception System.ArgumentNullException: Value cannot be null.~~Parameter name: path2~~~~Server stack trace: ~~   at System.IO.Path.Combine(String path1, String path2)~~   at Microsoft.ConfigurationManagement.ApplicationManagement.Wsfb.Sync.SyncConfig.get_OutboxDirectory()~~   at Microsoft.ConfigurationManagement.ApplicationManagement.Wsfb.Sync.SyncWorker.SetupOutbox()~~   at Microsoft.ConfigurationManagement.ApplicationManagement.Wsfb.Sync.SyncWorker.Start(String componentName)~~   at Microsoft.ConfigurationManager.TaskExecutionManager.TaskExecution.InvokeWorker(String assemblyToLoad, String typeToLoad, String componentName)~~   at System.Runtime.Remoting.Messaging.Message.Dispatch(Object target)~~   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)~~~~Exception rethrown at [0]: ~~   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)~~   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)~~   at Microsoft.ConfigurationManager.TaskExecutionManager.TaskExecution.InvokeWorker(String assemblyToLoad, String typeToLoad, String componentName)~~   at System.Threading.Tasks.Task.Execute()~~  $$<SMS_CLOUDCONNECTION><02-26-2023 19:56:04.252+480><thread=5988 (0x1764)>
The host's stop has been called, shutting down 2 workers.~~  $$<SMS_CLOUDCONNECTION><02-26-2023 19:56:04.252+480><thread=5988 (0x1764)>
Successfully shut down the workers.~~  $$<SMS_CLOUDCONNECTION><02-26-2023 19:56:04.284+480><thread=5988 (0x1764)>
Failed to initialize worker with error =  Unknown error 0x80131500  $$<SMS_CLOUDCONNECTION><02-26-2023 19:56:04.299+480><thread=5988 (0x1764)>
Thread for Task Execution Manager has stopped.  $$<SMS_CLOUDCONNECTION><02-26-2023 19:56:04.299+480><thread=5988 (0x1764)>
Stop for thread SMS_CLOUDCONNECTION has been called or Task Execution Manager thread has shutdown.  $$<SMS_CLOUDCONNECTION><02-26-2023 19:56:04.299+480><thread=6364 (0x18DC)>
The host's stop has been called, shutting down 0 workers.~~  $$<SMS_CLOUDCONNECTION><02-26-2023 19:56:04.299+480><thread=6364 (0x18DC)>
Successfully shut down the workers.~~  $$<SMS_CLOUDCONNECTION><02-26-2023 19:56:04.299+480><thread=6364 (0x18DC)>
End main SMS_CLOUDCONNECTION thread  $$<SMS_CLOUDCONNECTION><02-26-2023 19:56:04.299+480><thread=6364 (0x18DC)>
